name: k6 Performance Test

on: [push]

jobs:
  k6-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install k6
      run: |
        sudo apt update
        sudo apt install -y wget
        wget -q https://github.com/grafana/k6/releases/download/v0.42.0/k6-v0.42.0-linux-amd64.tar.gz
        tar -xvf k6-v0.42.0-linux-amd64.tar.gz
        sudo mv k6-v0.42.0-linux-amd64/k6 /usr/local/bin/
        rm -rf k6-v0.42.0-linux-amd64 k6-v0.42.0-linux-amd64.tar.gz

    - name: Run k6 test
      run: |
        k6 run k6-tests/script.js
